#!/bin/bash
CURRENT_DIR=$(pwd -P)
if [ -d "$CURRENT_DIR"/html ];
then
    rm -rf "$CURRENT_DIR"/html
fi
PROJECT_NAME=cJSON-1.7.17
VERSION=1.7.17
OUTPUT_DIRECTORY=$CURRENT_DIR/html
DATA_DIRECTORY=./data
BUILD_DIRECTORY=$CURRENT_DIR
SOURCE_DIRECTORY=$CURRENT_DIR
# cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
codebrowser_generator -b "$BUILD_DIRECTORY" -a -o "$OUTPUT_DIRECTORY" -p "$PROJECT_NAME":"$SOURCE_DIRECTORY":"$VERSION" -d "$DATA_DIRECTORY"
codebrowser_indexgenerator "$OUTPUT_DIRECTORY" -d "$DATA_DIRECTORY"
cp -rv ./data "$OUTPUT_DIRECTORY"
